############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "SPL Welcome"
url = "spl/"
weight = 3

[[main]]
name = "Parents Message"
url = "parents/"
weight = 4

[[main]]
name = "Calendar"
url = "calendar/"
weight = 5

[[main]]
name = "Contact"
url = "contact/"
weight = 6

[[main]]
name = "Join"
url = "join/"
weight = 7

#
# [[main]]
# weight = 4
# name = "Pages"
# hasChildren = true
#
# [[main]]
# parent = "Pages"
# name = "Blog"
# url = "blog/"
#
# [[main]]
# parent = "Pages"
# name = "Contact"
# url = "contact/"
#
# [[main]]
# parent = "Pages"
# name = "Authors"
# url = "authors/"
#
# [[main]]
# parent = "Pages"
# name = "Categories"
# url = "categories/"
#
# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "404/"
#

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Elements"
url = "elements/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
